
// This replaces the frontend hardcoded data.
// In a real scenario, this would be a MongoDB or PostgreSQL connection.

const experience = [
  {
    id: 1,
    title: "Psb Intralogistics",
    category: "Assistant Engineer",
    category_fr: "Ingénieur Assistant",
    category_de: "Assistenzingenieur",
    year: "Current",
    year_fr: "Actuel",
    year_de: "Aktuell",
    image: "https://picsum.photos/id/4/1920/1080",
    description: "Creating reports, planning technical projects, and optimizing production processes. Working deeply with automation systems and logic control.",
    description_fr: "Création de rapports, planification de projets techniques et optimisation des processus de production. Travail approfondi sur les systèmes d'automatisation.",
    description_de: "Erstellung von Berichten, Planung technischer Projekte und Optimierung von Produktionsprozessen. Tiefe Einarbeitung in Automatisierungssysteme.",
    details: "As an Assistant Engineer, I play a crucial role in the planning and execution of technical projects. My daily tasks involve creating detailed reports that drive decision-making and optimizing production processes to ensure maximum efficiency. I work closely with senior engineers to implement new intralogistics solutions.",
    stack: ["Project Management", "Optimization", "Reporting", "Logistics"]
  },
  {
    id: 2,
    title: "Lern-Academy",
    category: "Tutor",
    category_fr: "Tuteur",
    category_de: "Nachhilfelehrer",
    year: "2024",
    image: "https://picsum.photos/id/20/1920/1080",
    description: "Tutoring in Mathematics, Physics, French, English, and Biology.",
    description_fr: "Soutien scolaire en mathématiques, physique, français, anglais et biologie.",
    description_de: "Nachhilfeunterricht in Mathematik, Physik, Französisch, Englisch und Biologie.",
    details: "I provided comprehensive tutoring to students in various subjects including Mathematics, Physics, and Languages.",
    stack: ["Mathematics", "Physics", "Languages", "Pedagogy"]
  },
  {
    id: 3,
    title: "DCON GmbH",
    category: "Data Analyst",
    category_fr: "Analyste de Données",
    category_de: "Datenanalyst",
    year: "2023-2024",
    image: "https://picsum.photos/id/60/1920/1080",
    description: "Data analysis with Excel & SQL, process automation, and quality assurance.",
    description_fr: "Analyse de données avec Excel & SQL, automatisation des processus et assurance qualité.",
    description_de: "Datenanalyse mit Excel & SQL, Prozessautomatisierung und Qualitätssicherung.",
    details: "At DCON GmbH, I was responsible for analyzing large datasets using Excel and SQL to support business decisions.",
    stack: ["Excel", "SQL", "Data Analysis", "QA"]
  },
  {
    id: 4,
    title: "BMW",
    category: "Software Engineer",
    category_fr: "Ingénieur Logiciel",
    category_de: "Softwareingenieur",
    year: "2022-2023",
    image: "https://picsum.photos/id/180/1920/1080",
    description: "Software project planning, integration of new technologies, Python & JavaScript development.",
    description_fr: "Planification de projets logiciels, intégration de nouvelles technologies, développement Python & JavaScript.",
    description_de: "Planung von Softwareprojekten, Integration neuer Technologien, Entwicklung in Python & JavaScript.",
    details: "During my time at BMW, I contributed to the planning and analysis of software projects.",
    stack: ["Python", "JavaScript", "Software Architecture", "Automotive Tech"]
  }
];

const projects = [
    { 
      id: 200, 
      title: "VMed237", 
      category: "Quantum Health Ecosystem",
      category_fr: "Écosystème de Santé Quantique",
      category_de: "Quanten-Gesundheits-Ökosystem",
      description: "Medical quantum interface that will revolutionize the world of medicine.", 
      description_fr: "Interface quantique médicale qui va révolutionner le monde de la médecine.",
      description_de: "Medizinische Quantenschnittstelle, die die Welt der Medizin revolutionieren wird.",
      details: "VMed237 is a groundbreaking private initiative focused on creating a Quantum Health Ecosystem.",
      stack: ["Quantum Tech", "Medical AI", "React", "WebGL"],
      image: "https://images.unsplash.com/photo-1614935151651-0bea6508db6b?q=80&w=2525&auto=format&fit=crop", 
      private: true 
    },
    { id: 101, title: "Sales Dashboard", category: "Data Analysis", description: "Analyzed retail sales data using Python Pandas to identify seasonal trends.", stack: ["Python", "Pandas", "Matplotlib"] },
    { id: 102, title: "Customer Segmentation", category: "Data Science", description: "Clustered customer data using K-Means to target marketing campaigns.", stack: ["Python", "Scikit-Learn", "K-Means"] },
    { id: 103, title: "Churn Prediction", category: "Machine Learning", description: "Built a logistic regression model to predict customer churn.", stack: ["Python", "Logistic Regression", "ML"] },
    { id: 104, title: "Stock Analysis", category: "FinTech", description: "Visualized historical stock prices using Matplotlib and Yahoo Finance API.", stack: ["Python", "API", "Finance"] },
    { id: 105, title: "Weather Visualization", category: "Data Viz", description: "Created an interactive weather dashboard using D3.js and OpenWeatherMap.", stack: ["D3.js", "JavaScript", "API"] },
    { id: 106, title: "Sentiment Analysis", category: "NLP", description: "Processed Twitter data to gauge public sentiment on trending topics.", stack: ["Python", "NLTK", "Twitter API"] },
    { id: 107, title: "House Price Prediction", category: "Real Estate Tech", description: "Implemented a linear regression model for real estate valuation.", stack: ["Python", "Regression", "Data Science"] },
    { id: 108, title: "Supply Chain Opt.", category: "Logistics", description: "Simulated logistics network to minimize transportation costs using SciPy.", stack: ["Python", "SciPy", "Optimization"] },
    { id: 109, title: "Marketing ROI", category: "Business Intelligence", description: "Analyzed campaign performance metrics to optimize ad spend.", stack: ["Excel", "PowerBI", "Analytics"] },
    { id: 110, title: "Demographic Trends", category: "Sociology", description: "Visualized population growth trends using public census data.", stack: ["Python", "Seaborn", "Data Viz"] },
    { id: 111, title: "Personal Blog", category: "Web Dev", description: "Developed a static blog generator using Next.js and Markdown.", stack: ["Next.js", "React", "Markdown"] },
    { id: 112, title: "E-commerce Store", category: "Web Dev", description: "Built a mock online shop with cart functionality using React.", stack: ["React", "Redux", "Stripe"] },
    { id: 113, title: "Task Manager", category: "Productivity", description: "Created a Kanban-style todo app with drag-and-drop features.", stack: ["React", "DnD", "Firebase"] },
    { id: 114, title: "Recipe Finder", category: "Lifestyle", description: "Integrated a food API to search recipes based on ingredients.", stack: ["JavaScript", "Rest API", "CSS"] },
    { id: 115, title: "Fitness Tracker", category: "Health Tech", description: "Designed a dashboard to log and visualize workout progress.", stack: ["React", "Chart.js", "Node.js"] },
    { id: 116, title: "Real-time Chat", category: "Communication", description: "Implemented a real-time chat room using Socket.io and Node.js.", stack: ["Socket.io", "Node.js", "Express"] },
    { id: 117, title: "Weather Widget", category: "Web Components", description: "Built a lightweight JS widget for local weather updates.", stack: ["JavaScript", "HTML", "CSS"] },
    { id: 118, title: "Quiz Platform", category: "EdTech", description: "Developed a multiple-choice quiz engine with score tracking.", stack: ["Vue.js", "Firebase", "CSS"] },
    { id: 119, title: "Markdown Editor", category: "Dev Tools", description: "Created a browser-based markdown editor with live preview.", stack: ["React", "Regex", "Text Parsing"] },
    { id: 120, title: "Snippet Manager", category: "Dev Tools", description: "Built a tool to save and organize reusable code snippets.", stack: ["Electron", "JavaScript", "Local Storage"] },
    { id: 121, title: "Web Scraper", category: "Automation", description: "Python script to extract job listings from various career sites.", stack: ["Python", "BeautifulSoup", "Selenium"] },
    { id: 122, title: "File Organizer", category: "Automation", description: "Automating file sorting by extension using Python OS module.", stack: ["Python", "OS", "Automation"] },
    { id: 123, title: "Email Bot", category: "Automation", description: "Scripted automated email responses and notifications.", stack: ["Python", "SMTP", "Email"] },
    { id: 124, title: "PDF Merger", category: "Utilities", description: "Created a utility to merge and split PDF documents programmatically.", stack: ["Python", "PyPDF2", "Scripting"] },
    { id: 125, title: "Batch Image Resizer", category: "Media Processing", description: "Built a batch image processing tool using Pillow library.", stack: ["Python", "Pillow", "Image Processing"] },
    { id: 126, title: "Backup Script", category: "SysAdmin", description: "Automated daily directory backups to an external drive.", stack: ["Bash", "Cron", "Linux"] },
    { id: 127, title: "Log Analyzer", category: "DevOps", description: "Parsed server logs to generate traffic reports and error alerts.", stack: ["Python", "Regex", "Monitoring"] },
    { id: 128, title: "Discord Bot", category: "Bot Dev", description: "Programmed a bot for server moderation and music playback.", stack: ["Node.js", "Discord.js", "API"] },
    { id: 129, title: "Telegram Notifier", category: "Bot Dev", description: "Script to send system status updates to a Telegram channel.", stack: ["Python", "Telegram API", "Webhooks"] },
    { id: 130, title: "Data Cleaner", category: "Data Engineering", description: "Developed a pipeline to handle missing values in datasets.", stack: ["Python", "Pandas", "ETL"] },
    { id: 131, title: "Sudoku Solver", category: "Algorithms", description: "Implemented a backtracking algorithm to solve Sudoku puzzles.", stack: ["Python", "Algorithms", "Backtracking"] },
    { id: 132, title: "Pathfinding Visualizer", category: "Algorithms", description: "Visualized A* and Dijkstra algorithms on a grid.", stack: ["JavaScript", "Canvas", "Algorithms"] },
    { id: 133, title: "Sorting Visualizer", category: "Algorithms", description: "Animated Bubble, Merge, and Quick sort algorithms.", stack: ["React", "Algorithms", "Animation"] },
    { id: 134, title: "Fractal Generator", category: "Math", description: "Generated Mandelbrot set images using complex number math.", stack: ["Python", "NumPy", "Mathematics"] },
    { id: 135, title: "Prime Finder", category: "Math", description: "Optimized sieve algorithms to find large prime numbers.", stack: ["C++", "Mathematics", "Performance"] },
    { id: 136, title: "Matrix Calculator", category: "Math", description: "Built a tool for matrix multiplication and determinant calculation.", stack: ["Python", "NumPy", "Linear Algebra"] },
    { id: 137, title: "Graph Visualizer", category: "Graph Theory", description: "Visualized graph theory concepts like connectivity and cycles.", stack: ["D3.js", "Graph Theory", "Data Viz"] },
    { id: 138, title: "Pi Estimator", category: "Simulation", description: "Used Monte Carlo simulation to approximate the value of Pi.", stack: ["Python", "Statistics", "Simulation"] },
    { id: 139, title: "Game of Life", category: "Simulation", description: "Implemented Conway's Game of Life cellular automaton.", stack: ["JavaScript", "Canvas", "Automata"] },
    { id: 140, title: "Physics Simulator", category: "Simulation", description: "Created a 2D physics engine for collision detection.", stack: ["C++", "Physics", "Mechanics"] },
    { id: 141, title: "Digit Recognizer", category: "Deep Learning", description: "Trained a CNN on MNIST dataset to recognize handwritten digits.", stack: ["Python", "TensorFlow", "Deep Learning"] },
    { id: 142, title: "Spam Filter", category: "AI", description: "Built a Naive Bayes classifier to detect spam emails.", stack: ["Python", "Scikit-Learn", "NLP"] },
    { id: 143, title: "Movie Recommender", category: "AI", description: "Implemented collaborative filtering for movie suggestions.", stack: ["Python", "Pandas", "Recommender Systems"] },
    { id: 144, title: "Face Detector", category: "Computer Vision", description: "Used OpenCV Haar Cascades for real-time face detection.", stack: ["Python", "OpenCV", "Vision"] },
    { id: 145, title: "Translator Tool", category: "API Integration", description: "Integrated Google Translate API for a multi-language tool.", stack: ["JavaScript", "API", "Translation"] },
    { id: 146, title: "Text Summarizer", category: "NLP", description: "Used NLP techniques to summarize long articles.", stack: ["Python", "HuggingFace", "Transformers"] },
    { id: 147, title: "Voice Assistant", category: "AI", description: "Built a simple voice command recognition tool.", stack: ["Python", "SpeechRecognition", "Audio"] },
    { id: 148, title: "Object Detection", category: "Computer Vision", description: "Experimented with YOLO for identifying objects in images.", stack: ["Python", "YOLO", "Computer Vision"] },
    { id: 149, title: "Music Classifier", category: "Audio AI", description: "Analyzed audio features to classify music genres.", stack: ["Python", "Librosa", "Audio Processing"] },
    { id: 150, title: "Credit Scoring", category: "FinTech", description: "Built a decision tree model to assess loan risk.", stack: ["Python", "Decision Trees", "Risk Analysis"] }
];

module.exports = { experience, projects };
